### ISSUE TITLE
How to compile on macOS

### ISSUE THREAD

**Issue by Yukino0319** [MuntashirAkon/hostap_realtek_osx#1]
Hi Muntashir,
I am a newcomer in macOS and interested in this project. When i download the whole code and `make` it, too many error occur to me, 
for example `netpacket/packet.h not found`, and i know packet.h is in Linux.
 Do I need to modify 'configure' or other config files? How can i success to compile it on macOS?
Thanks a lot!

**Comment by MuntashirAkon** [comment]
The purpose of this project is to build a wpa_supplicant for OS X so that we can continue to use RTL8188* wireless adapters after Apple drops support for 32 bit apps (the app that comes with this adapter is 32 bit). That saying, here's a brief description of how you can compile wpa_supplicant (for the above driver only) on macOS:

In **/src/drivers/drivers.mak** add the following lines to enable `driver_osx_other` driver:
```make
ifdef CONFIG_DRIVER_OSX
DRV_CFLAGS += -DCONFIG_DRIVER_OSX
DRV_OBJS += ../src/drivers/driver_osx_other.o
NEED_DRV_WIRED_COMMON=0
endif
```

Comment out the following lines in **/wpa_supplicant/Makefile**:
```make
echo CONFIG_DRIVER_HOSTAP=y >> .config
echo CONFIG_DRIVER_WEXT=y >> .config
```

And the [.config](https://github.com/MuntashirAkon/hostap_realtek_osx/files/3033005/config.txt) file to be copied at **/wpa_supplicant**.

**Comment by Yukino0319** [comment]
thank u, it works for me! :+1:

**Comment by aleung** [comment]
I got error:

> hostap_realtek_osx-master/src/common/dhcp.h:46:15: error: field has
>       incomplete type 'struct iphdr'

Searched this error and knew that `iphdr` is not available on macOS. Add a line for workaround and it passed.

``` c
#define iphdr ip
```

**Comment by MuntashirAkon** [comment]
@aleung Did you follow https://github.com/MuntashirAkon/hostap_realtek_osx/issues/1#issuecomment-478899065 properly? This error shouldn't occur.
