### ISSUE TITLE
FindRTL8180 return failed

### ISSUE THREAD

**Issue by Yukino0319** [MuntashirAkon/hostap_realtek_osx#3]
Hi Muntashir,
when i use wpa_supplicant on macOS 10.14, it returns `Failed to initialize driver interface`.
in function FindRTL8180 (driver_osx_other.c:68)
```c
matching = IOServiceMatching(services[i]);
if (matching)
{
	result = IOServiceGetMatchingServices(masterPort, matching, &iterator);	
        if (!result)
	{
		service = IOIteratorNext(iterator);
		if (service)
		{
			result = IOServiceOpen(service, mach_task_self_, 0, &connect);
			break;
		}
		IOObjectRelease(iterator);
	}
}
```
service is 0, `(matching && !result) = true`
I have downloaded realtek-rtl8180 driver from https://www.wireless-driver.com/realtek-rtl8180-wireless-lan-mini-pci-nic/, but it doesnt work.
how can i connect to wireless network? thank u.

**Comment by Yukino0319** [comment]
for more, does it support both 802.11n ans 802.11ac?

**Comment by Yukino0319** [comment]
I have solved it.
there is USB_RTL8812AU+ SKY85703_driver_mac.zip which i need to install.
could i commit it to this project?

**Comment by MuntashirAkon** [comment]
> when i use wpa_supplicant on macOS 10.14, it returns `Failed to initialize driver interface`.

This is a work in progress. So, some devices may not work as expected. I'm currently running Mojave where `wpa_supplicant` works for RTL8188EU device.

It should also be noted that, this is just a client, not the driver itself. Realtek didn't release any source code for RTL818* devices' kernel extensions. That means, in order to get to work, you must install **RtWlanU** and **RtWlanU1827** kexts (these kext are installed when you ran the **Installer.pkg**).

That saying, you probably didn't install the above kexts when you used `wpa_supplicant`. As a result it couldn't find the device.

> how can i connect to wireless network?

This approach is similar to Linux. Search online on how to use `wpa_supplicant` to connect to Wifi. You can also use `wpa_gui.app`, but that's another story (I can send you a prebuilt binary if you badly need one). But be aware of issue #2.

> does it support both 802.11n ans 802.11ac?

It should support both. I haven't tested it though. But I've enabled both in `.config` file.

> could i commit it to this project?

Let me tell you why I've started this project: the current binary works but the **StatusBarApp.app** (the GUI app in the status bar which allows you to connect to Wifi network) is 32 bit (the drivers are 64 bit). Since 32 bit app will not work on macOS 10.15, a 64 bit alternative client is needed.

I've been looking at the **StatusBarApp.app** binary for sometime to reverse engineer (in some level, at least) so that we can at least have some basic functionality on coming macOS 10.15.

**Comment by Yukino0319** [comment]
thanks for your reply.
I have installed RTL* drivers. RtWlanU and RtWlanU1827 kexts exsit in /System/Library/Extensions.
wpa_supplicant is running successfully on VMware, but failing on physical machine.
Is there any possible to use native drivers in Mojave with wpa_suplicant?

**Comment by MuntashirAkon** [comment]
> wpa_supplicant is running successfully on VMware, but failing on physical machine.

No idea it is not working for you. It is working great on my machine (running Mojave 10.14.5 beta 3).

`Failed to initialize driver interface` means that RtWlanU is probably not attached to the device.

Give me an ioreg output after inserting the device.

> Is there any possible to use native drivers in Mojave with wpa_suplicant?

Probably. CoreWLAN is not enough for this as it doesn't provide all the required features. As far as I know nobody has tried to reverse engineer Apple80211 framework on Mojave yet.

**Comment by Yukino0319** [comment]
Thanks a lot!
